CREATE TABLE [sales].[RAW_Sales]
(
    [IDSeller] int,
    [SellerName] nvarchar(255),
    [SaleDate] DATETIME,
    [ExpirationDate] DATETIME,
    [OrderNumber] nvarchar(255),
    [ManagerName] nvarchar(255),
    [IDBranch] INT,
    [BranchName] nvarchar(255),
    [BranchCityName] nvarchar(255),
    [BranchCountry] nvarchar(255),
    [BranchPopulation] INT,
    [IDProduct] INT,
    [ProductName] nvarchar(255),
    [IDCategory] INT,
    [CategoryName] nvarchar(255),
    [IDSubcategory] INT,
    [SubcategoryName] nvarchar(255),
    [CostPrice] money,
    [SellPrice] money,
    [Margin] MONEY,
    [MarginPercet] NUMERIC(18, 4),
    [IDCustomer] INT,
    [CustomerName] nvarchar(255),
    [CustomerCityCode] INT,
    [CustomerCityName] nvarchar(255),
    [CustomerCountry] nvarchar(255),
    [CustomerCityPopulation] INT,
    [UnitPrice] money,
    [Quantity] NUMERIC(18, 4),
    [SellTotal] money,
    [Discount] money,
    [DiscountPercent] NUMERIC(18, 4),
    [Payment] money,
    [PaymentDate] DATETIME,
    [IDManager] int
    )
GO
